### ISSUE TITLE
Token limit far too small

### ISSUE THREAD

**Issue by bcatalfo** [WICG/writing-assistance-apis#11]
Because the token limit is so small it is hard to summarize news articles.

In a certain way this is a feature, however. I have some ideas for hacking around this. If the token limit was bigger my project would be too easy!

**Comment by domenic** [comment]
This appears to be a feature request to a specific implementation of this API (probably Chrome's), and as such not suitable for the specification repository. (No token limits are provided in the explainer, as you can see by reading it in full.) So, I will close this, and encourage you to file a more-detailed issue on the appropriate browser bug tracker.
