### ISSUE TITLE
Writer API in promise 

### ISSUE THREAD

**Issue by space-techy** [WICG/writing-assistance-apis#13]
***Issue Description***
When attempting to create a writer instance using the following code snippet:
```
const check = await ai.writer.create();
```
The promise is not resolving as expected. This issue persists consistently and was not present earlier. Initially, the promise resolved correctly, and the functionality worked as intended.

***Steps to reproduce***
1. Use the ai.writer.create() method in an async function.
2. Await the result.
3. Observe that the promise does not resolve.

***Expected Behavior***
The ai.writer.create() method should resolve the promise and return the desired output as it did previously.

***Actual Behavior***
The promise remains unresolved, and the method does not return the expected output.

**Comment by domenic** [comment]
This appears to be a request for support with some specific implementation of this API, probably Chrome's. In that case, it's better filed on that project's bug tracker (for Chrome that's https://crbug.new/). This repository is for discussing the standardization of the API and not specific implementations.

**Comment by tomayac** [comment]
(This is a known issue, see https://developer.chrome.com/docs/ai/built-in-apis#api_status for the bug link.)
