### ISSUE TITLE
Function calling: will the prompt api support it?

### ISSUE THREAD

**Issue by M-JULIANI** [WICG/writing-assistance-apis#20]
Hello,

I didn't see any mention of function-calling. It's a very useful paradigm and way to structure workflows. I didn't see any mention of this (one clear use case is deciding when to use one api, another, or reaching for storage).

Thanks,
Marco

**Comment by christianliebel** [comment]
Hi Marco, this is the repository for the Writing Assistance APIs (Writer, Rewriter, Summarizer API). The following issue in the Prompt API repository is about adding function calling: https://github.com/explainers-by-googlers/prompt-api/issues/7

**Comment by M-JULIANI** [comment]
thank you will close this out
