### ISSUE TITLE
Ergonomics of checking supported options

### ISSUE THREAD

**Issue by michaelwasserman** [WICG/writing-assistance-apis#21]
The explainer suggests a sync `summarizerCapabilities.createOptionsAvailable({ type: "teaser" });`
(tangentially Chromium currently implements a `summarizerCapabilities.supportsType("teaser")`)

How will devs know the set of potential option enum values, will they need to check docs and source?

It seems more ergonomic to supply a read-only `SummarizerCapabilities.supportedTypes` array or similar.
`createOptionsAvailable` could still answer whether combinations of e.g. type+length are supported together.

**Comment by domenic** [comment]
Checking the docs for enum values, like all other web APIs, is indeed the recommended pattern. A `supportedTypes` array would be misleading because of the not-supported combinations.
