### ISSUE TITLE
Explain benefits over the Prompt API or a chat API

### ISSUE THREAD

**Issue by scblaze** [WICG/writing-assistance-apis#8]
The Explainer for these API's mentions the Prompt API: https://github.com/explainers-by-googlers/prompt-api/

However, there isn't really an explanation of why these higher level API's are preferable to a Prompt API interface. It would be helpful to add it.

As a developer, I can't help but feel that these higher-level APIs seem much more restrictive and less useful compared to a general Prompt API. It seems like this higher-level functionality would make more sense to leave to library authors and that browsers should focus on lower level building blocks like an instruct-type Prompt API or maybe even a chat API.

**Comment by domenic** [comment]
The explainer does cover this: https://github.com/WICG/writing-assistance-apis/blob/main/README.md#directly-exposing-a-prompt-api :)
